window.translations_es = {
  app_title: "Detector de acordes para guitarra",
  main_title: "Detector de acordes",
  subtitle:
    "Elige afinación (incluso personalizada), escribe los trastes y te digo qué acorde es.",
  label_tuning: "Afinación:",
  label_notation: "Notación:",
  label_language: "Idioma:",
  label_show_octave: "Mostrar Octava",
  notation_latin: "Latina (Do, Re, Mi...)",
  notation_anglo: "Anglosajona (C, D, E...)",
  label_tuning_name: "Nombre afinación:",
  placeholder_tuning_name: "Mi afinación",
  btn_save_tuning: "Guardar afinación",
  header_string: "Cuerda",
  header_tuning: "Afinación",
  header_fret: "Traste",
  header_note: "Nota",
  string_label_prefix: "Cuerda",
  placeholder_fret: "0, 1, 3, x... (Trastes)",
  btn_calc: "Calcular acorde",
  hint_text:
    "• Deja la casilla de traste vacía o escribe <strong>x</strong> si esa cuerda no suena.<br /> • Usa números de <strong>0 a 24</strong> para los trastes.<br /> • En afinación, haz clic en cada cuerda para elegir la nota desde un desplegable.<br /> • Escribe un nombre y pulsa <strong>Guardar afinación</strong> para guardarla en el navegador.",
  msg_error_data: "Error en los datos",
  msg_no_notes: "Sin notas",
  tuning_e_std: "E estándar",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D estándar",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  group_builtin: "Predefinidas",
  group_custom: "Personalizadas",
  chord_major: "Mayor",
  chord_minor: "Menor",
  chord_dim: "Disminuido",
  chord_aug: "Aumentado",
  chord_sus2: "Suspendido 2",
  chord_sus4: "Suspendido 4",
  chord_maj7: "Mayor 7",
  chord_m7: "Menor 7",
  chord_dom7: "Dominante 7",
  chord_m7b5: "Semidisminuido 7",
  chord_dim7: "Disminuido 7",
  chord_mmaj7: "Menor mayor 7",
  chord_maj6: "Mayor 6",
  chord_m6: "Menor 6",
  single_note: "Nota aislada",
  power_chord: "Power chord (quinta justa)",
  msg_enter_name: "Escribe un nombre para la afinación personalizada.",
  msg_error_reading_strings:
    "No se ha podido leer la afinación de las cuerdas.",
  msg_unknown_chord: "Acorde no reconocido",
  msg_notes_detected: "Notas detectadas: ",
  msg_type: "Tipo: ",
  msg_notes: " | Notas: ",
};
