window.translations_es = {
  app_title: "Detector de acordes para guitarra",
  main_title: "Detector de acordes",
  subtitle:
    "Toca una nota o un acorde. El sistema intentará adivinar la nota, cuerda/traste y, si es posible, el acorde.",
  label_tuning: "Afinación:",
  label_notation: "Notación:",
  label_language: "Idioma:",
  label_show_octave: "Mostrar Octava",
  notation_latin: "Latina (Do, Re, Mi...)",
  notation_anglo: "Anglosajona (C, D, E...)",
  label_tuning_name: "Nombre afinación:",
  placeholder_tuning_name: "Mi afinación",
  btn_save_tuning: "Guardar afinación",
  header_string: "Cuerda",
  header_tuning: "Afinación",
  header_fret: "Traste",
  header_note: "Nota",
  string_label_prefix: "Cuerda",
  placeholder_fret: "0, 1, 3, x... (Trastes)",
  btn_calc: "Calcular acorde",
  hint_text:
    "Consejo: usa una <strong>guitarra bien afinada</strong>, toca limpiamente cerca del micrófono y evita el ruido de fondo.<br>La detección de acordes es aproximada (no tan precisa como un plugin dedicado).",
  msg_error_data: "Error en los datos",
  msg_no_notes: "Sin notas",
  tuning_e_std: "E estándar",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D estándar",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  group_builtin: "Predefinidas",
  group_custom: "Personalizadas",
  chord_major: "Mayor",
  chord_minor: "Menor",
  chord_dim: "Disminuido",
  chord_aug: "Aumentado",
  chord_sus2: "Suspendido 2",
  chord_sus4: "Suspendido 4",
  chord_maj7: "Mayor 7",
  chord_m7: "Menor 7",
  chord_dom7: "Dominante 7",
  chord_m7b5: "Semidisminuido 7",
  chord_dim7: "Disminuido 7",
  chord_mmaj7: "Menor mayor 7",
  chord_maj6: "Mayor 6",
  chord_m6: "Menor 6",
  single_note: "Nota aislada",
  power_chord: "Power chord (quinta justa)",
  msg_enter_name: "Escribe un nombre para la afinación personalizada.",
  msg_error_reading_strings:
    "No se ha podido leer la afinación de las cuerdas.",
  msg_unknown_chord: "Acorde no reconocido",
  msg_notes_detected: "Notas detectadas: ",
  msg_type: "Tipo: ",
  msg_notes: " | Notas: ",
  advanced_settings_title: "Ajustes avanzados de detección",
  label_history_window: "Ventana historial notas (ms)",
  label_min_notes: "Mín. notas distintas para acorde",
  label_max_deviation: "Desviación máx. (cents)",
  label_note_hold_time: "Tiempo retención nota (ms)",
  label_chord_min_quality: "Calidad mínima acorde (0-1)",
  label_min_volume_rms: "Umbral de volumen (RMS)",
  btn_save_settings: "Guardar ajustes",
  btn_reset_settings: "Reset a valores por defecto",
  label_logs_debug: "Logs / Debug",
  label_enable_logs: "Activar logs",
  btn_clear_logs: "Limpiar",
  msg_logs_enabled: "Logs activados.",
  msg_settings_loaded:
    "Ajustes avanzados cargados (ventana={0}ms, mín notas={1}, max desv={2}cents, hold={3}ms, calidad={4}, vol={5})",
  msg_settings_saved:
    "Ajustes avanzados guardados (ventana={0}ms, mín notas={1}, max desv={2}cents, hold={3}ms, calidad={4}, vol={5})",
  msg_settings_reset: "Ajustes avanzados reseteados a valores por defecto.",
  msg_note_detected: "Nota detectada",
  msg_chord_detected: "Acorde detectado",
  msg_no_clear_note: "No hay nota clara",
  msg_deviation: "Hz · desviación",
  msg_cents: "cents",
  msg_approx: "(aprox)",
  msg_suggested_note: "Nota en posición sugerida:",
  msg_detected_notes: "notas detectadas:",
  err_no_audiocontext: "AudioContext no soportado",
  btn_stop: "Detener Escucha",
  btn_start: "Iniciar Escucha",
  status_listening: "Escuchando",
  status_stopped: "Detenido",
  err_mic_access: "Error acceso micro:",
  msg_interval_saved: "Intervalo guardado.",
  label_interval: "Actualización (ms):",
  btn_save_interval: "Guardar intervalo",
  label_chord_detected: "Acorde Detectado",
  label_main_note: "Nota Principal",
  label_string_fret: "Cuerda / traste sugeridos",
  msg_play_chord: "Toca varias cuerdas para intentar detectar un acorde.",
};
