window.translations_en = {
  app_title: "Guitar Chord Detector",
  main_title: "Chord Detector",
  subtitle:
    "Play a note or a guitar chord. The system will try to guess the note, string/fret and, if possible, the chord.",
  label_tuning: "Tuning:",
  label_notation: "Notation:",
  label_language: "Language:",
  label_show_octave: "Show Octave",
  notation_latin: "Latin (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_tuning_name: "Tuning Name:",
  placeholder_tuning_name: "My tuning",
  btn_save_tuning: "Save Tuning",
  header_string: "String",
  header_tuning: "Tuning",
  header_fret: "Fret",
  header_note: "Note",
  string_label_prefix: "String",
  placeholder_fret: "0, 1, 3, x...",
  btn_calc: "Calculate Chord",
  hint_text:
    "Hint: use a <strong>well-tuned guitar</strong>, play cleanly near the mic and avoid background noise.<br>Chord detection is approximate (not as precise as a dedicated plugin).",
  msg_error_data: "Data error",
  msg_no_notes: "No notes",
  tuning_e_std: "E Standard",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D Standard",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  group_builtin: "Built-in",
  group_custom: "Custom",
  chord_major: "Major",
  chord_minor: "Minor",
  chord_dim: "Diminished",
  chord_aug: "Augmented",
  chord_sus2: "Suspended 2",
  chord_sus4: "Suspended 4",
  chord_maj7: "Major 7",
  chord_m7: "Minor 7",
  chord_dom7: "Dominant 7",
  chord_m7b5: "Half-diminished 7",
  chord_dim7: "Diminished 7",
  chord_mmaj7: "Minor Major 7",
  chord_maj6: "Major 6",
  chord_m6: "Minor 6",
  single_note: "Single Note",
  power_chord: "Power Chord",
  msg_enter_name: "Please enter a name for the custom tuning.",
  msg_error_reading_strings: "Could not read string tuning.",
  msg_unknown_chord: "Unknown Chord",
  msg_notes_detected: "Notes detected: ",
  msg_type: "Type: ",
  msg_notes: " | Notes: ",
  advanced_settings_title: "Advanced Detection Settings",
  label_history_window: "Note History Window (ms)",
  label_min_notes: "Min. Distinct Notes for Chord",
  label_max_deviation: "Max. Deviation (cents)",
  label_note_hold_time: "Note Hold Time (ms)",
  label_chord_min_quality: "Min. Chord Quality (0-1)",
  label_min_volume_rms: "Volume Threshold (RMS)",
  btn_save_settings: "Save Settings",
  btn_reset_settings: "Reset to Defaults",
  label_logs_debug: "Logs / Debug",
  label_enable_logs: "Enable Logs",
  btn_clear_logs: "Clear",
  msg_logs_enabled: "Logs enabled.",
  msg_settings_loaded:
    "Advanced settings loaded (window={0}ms, min notes={1}, max dev={2}cents, hold={3}ms, quality={4}, vol={5})",
  msg_settings_saved:
    "Advanced settings saved (window={0}ms, min notes={1}, max dev={2}cents, hold={3}ms, quality={4}, vol={5})",
  msg_settings_reset: "Advanced settings reset to default.",
  msg_note_detected: "Note detected",
  msg_chord_detected: "Chord detected",
  msg_no_clear_note: "No clear note",
  msg_deviation: "Hz · deviation",
  msg_cents: "cents",
  msg_approx: "(approx)",
  msg_suggested_note: "Note at suggested position:",
  msg_detected_notes: "detected notes:",
  err_no_audiocontext: "AudioContext not supported",
  btn_stop: "Stop Listening",
  btn_start: "Start Listening",
  status_listening: "Listening",
  status_stopped: "Stopped",
  err_mic_access: "Mic access error:",
  msg_interval_saved: "Interval saved.",
  label_interval: "Update (ms):",
  btn_save_interval: "Save interval",
  label_chord_detected: "Detected Chord",
  label_main_note: "Main Note",
  label_string_fret: "Suggested String / Fret",
  msg_play_chord: "Play multiple strings to try to detect a chord.",
};
