window.translations_es = {
  tool_library_title: "Biblioteca de acordes",
  tool_library_desc:
    "Explora una completa biblioteca de acordes de guitarra con posiciones de dedos y múltiples voces.",
  label_tuning: "Afinación:",
  label_notation: "Notación:",
  notation_latin: "Latina (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_language: "Idioma:",
  label_sound_profile: "Sonido:",
  sound_clean: "Guitarra limpia",
  sound_jazz: "Guitarra jazz",
  sound_dist1: "Distorsión 1",
  sound_dist2: "Distorsión 2",
  label_custom_tunings: "Afinaciones personalizadas",
  tuning_e_std: "E estándar",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D estándar",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  tuning_drop_e: "Drop E",
  tuning_c_std: "C estándar",
  tuning_b_std: "B estándar",
  tuning_a_std: "A estándar",
  label_show_octave: "Mostrar octava",
  label_detected: "(Detectado)",
  btn_back: "Volver",
  label_root: "Tónica",
  label_type: "Tipo",
  type_maj: "Mayor",
  type_min: "Menor",
  prompt_tuning_name: "Introduce el nombre de la afinación:",
  confirm_delete_tuning: "¿Estás seguro de que quieres eliminar esta afinación?",
  type_7: "7",
  type_5: "5",
  type_6: "6",
  type_m6: "m6",
  type_maj7: "maj7",
  type_m7: "m7",
  type_m7b5: "m7b5",
  type_dim: "disminuido",
  type_dim7: "dim7",
  "type_m(maj7)": "m(maj7)",
  type_9: "9",
  type_maj9: "maj9",
  type_m9: "m9",
  type_11: "11",
  type_m11: "m11",
  type_13: "13",
  type_maj13: "maj13",
  type_m13: "m13",
  "type_6/9": "6/9",
  type_sus2: "sus2",
  type_sus4: "sus4",
  type_7sus4: "7sus4",
  type_7b5: "7b5",
  type_7b9: "7b9",
  type_9sus4: "9sus4",
  type_add9: "add9",
  type_aug: "aum",
  type_aug9: "aug9",
  finger_index: "Índice",
  finger_middle: "Medio",
  finger_ring: "Anular",
  finger_pinky: "Meñique",

  // Advanced Settings
  advanced_settings: "Ajustes avanzados",
  pitch_shift: "Cambio de tono",
  shift_full: "Cambio (rango completo)",
  shift_octaves: "Cambio (octavas)",
  shift_semitonos: "Cambio (semitonos)",
  shift_cents: "Cambio (centésimas)",
  formant_shift: "Cambio de formante",
  formant_full: "Formante (completo)",
  formant_semitones: "Formante (semitonos)",
  formant_cents: "Formante (centésimas)",
  btn_reset_defaults: "Restablecer valores",

  // Custom Chords
  btn_save_chord: "Guardar acorde",
  btn_delete_chord: "Eliminar acorde",
  prompt_chord_name: "Introduce el nombre del acorde:",
  confirm_delete_chord: "¿Estás seguro de que quieres eliminar este acorde?",
  label_custom_chords: "Mis acordes",
  msg_chord_saved: "¡Acorde guardado!",
  msg_chord_deleted: "¡Acorde eliminado!",
  
  // Instructions
  instr_drag_note: "Arrastra para mover notas",
  instr_barre: "Doble clic para crear cejilla",
  instr_barre_finish: "Clic para finalizar cejilla",
  instr_context_menu: "Clic derecho para más opciones",
  unknown_chord: "Acorde desconocido",
  
  // Context Menu
  ctx_add_note: "Añadir nota",
  ctx_remove_note: "Quitar nota",
  ctx_open_string: "Cuerda al aire",
  ctx_mute_string: "Mutear cuerda"
};
