window.translations_es = {
  tool_library_title: "Biblioteca de Acordes",
  tool_library_desc:
    "Explora una completa biblioteca de acordes de guitarra con posiciones de dedos y múltiples voces.",
  label_tuning: "Afinación:",
  label_notation: "Notación:",
  notation_latin: "Latina (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_language: "Idioma:",
  label_show_octave: "Mostrar Octava",
  btn_back: "Volver",
  label_root: "Tónica",
  label_type: "Tipo",
  type_maj: "Mayor",
  type_min: "Menor",
  type_7: "7",
  type_5: "5",
  type_6: "6",
  type_m6: "m6",
  type_maj7: "maj7",
  type_m7: "m7",
  type_m7b5: "m7b5",
  type_dim: "disminuido",
  type_dim7: "dim7",
  "type_m(maj7)": "m(maj7)",
  type_9: "9",
  type_maj9: "maj9",
  type_m9: "m9",
  type_11: "11",
  type_m11: "m11",
  type_13: "13",
  type_maj13: "maj13",
  type_m13: "m13",
  "type_6/9": "6/9",
  type_sus2: "sus2",
  type_sus4: "sus4",
  type_7sus4: "7sus4",
  type_7b5: "7b5",
  type_7b9: "7b9",
  type_9sus4: "9sus4",
  type_add9: "add9",
  type_aug: "aum",
  type_aug9: "aug9",
  finger_index: "Índice",
  finger_middle: "Medio",
  finger_ring: "Anular",
  finger_pinky: "Meñique",
};
