window.translations_en = {
  tool_library_title: "Chord library",
  tool_library_desc:
    "Explore a comprehensive library of guitar chords with finger positions and multiple voicings.",
  label_tuning: "Tuning:",
  label_notation: "Notation:",
  notation_latin: "Latin (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_language: "Language:",
  label_sound_profile: "Sound:",
  sound_clean: "Clean guitar",
  sound_jazz: "Jazz guitar",
  sound_dist1: "Distortion 1",
  sound_dist2: "Distortion 2",
  label_custom_tunings: "Custom tunings",
  tuning_e_std: "E standard",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D standard",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  tuning_c_std: "C standard",
  tuning_b_std: "B standard",
  tuning_a_std: "A standard",
  label_show_octave: "Show octave",
  btn_back: "Back",
  label_root: "Root",
  label_type: "Type",
  type_maj: "maj",
  type_min: "min",
  prompt_tuning_name: "Enter tuning name:",
  confirm_delete_tuning: "Are you sure you want to delete this tuning?",
  type_7: "7",
  type_5: "5",
  type_6: "6",
  type_m6: "m6",
  type_maj7: "maj7",
  type_m7: "m7",
  type_m7b5: "m7b5",
  type_dim: "dim",
  type_dim7: "dim7",
  "type_m(maj7)": "m(maj7)",
  type_9: "9",
  type_maj9: "maj9",
  type_m9: "m9",
  type_11: "11",
  type_m11: "m11",
  type_13: "13",
  type_maj13: "maj13",
  type_m13: "m13",
  "type_6/9": "6/9",
  type_sus2: "sus2",
  type_sus4: "sus4",
  type_7sus4: "7sus4",
  type_7b5: "7b5",
  type_7b9: "7b9",
  type_9sus4: "9sus4",
  type_add9: "add9",
  type_aug: "aug",
  type_aug9: "aug9",
  finger_index: "Index",
  finger_middle: "Middle",
  finger_ring: "Ring",
  finger_pinky: "Pinky",
  
  // Advanced Settings
  advanced_settings: "Advanced settings",
  pitch_shift: "Pitch shift",
  shift_full: "Shift (full range)",
  shift_octaves: "Shift (octaves)",
  shift_semitones: "Shift (semitones)",
  shift_cents: "Shift (cents)",
  formant_shift: "Formant shift",
  formant_full: "Formant (full)",
  formant_semitones: "Formant (semitones)",
  formant_cents: "Formant (cents)",
  btn_reset_defaults: "Reset defaults",
};
