window.translations_en = {
  tool_library_title: "Chord Library",
  tool_library_desc:
    "Explore a comprehensive library of guitar chords with finger positions and multiple voicings.",
  label_tuning: "Tuning:",
  label_notation: "Notation:",
  notation_latin: "Latin (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_language: "Language:",
  label_sound_profile: "Sound:",
  sound_clean: "Clean Guitar",
  sound_jazz: "Jazz Guitar",
  label_show_octave: "Show Octave",
  btn_back: "Back",
  label_root: "Root",
  label_type: "Type",
  type_maj: "maj",
  type_min: "min",
  type_7: "7",
  type_5: "5",
  type_6: "6",
  type_m6: "m6",
  type_maj7: "maj7",
  type_m7: "m7",
  type_m7b5: "m7b5",
  type_dim: "dim",
  type_dim7: "dim7",
  "type_m(maj7)": "m(maj7)",
  type_9: "9",
  type_maj9: "maj9",
  type_m9: "m9",
  type_11: "11",
  type_m11: "m11",
  type_13: "13",
  type_maj13: "maj13",
  type_m13: "m13",
  "type_6/9": "6/9",
  type_sus2: "sus2",
  type_sus4: "sus4",
  type_7sus4: "7sus4",
  type_7b5: "7b5",
  type_7b9: "7b9",
  type_9sus4: "9sus4",
  type_add9: "add9",
  type_aug: "aug",
  type_aug9: "aug9",
  finger_index: "Index",
  finger_middle: "Middle",
  finger_ring: "Ring",
  finger_pinky: "Pinky",
};
