window.translations_en = {
  app_title: "Guitar chord by fret",
  main_title: "Chord by fret",
  subtitle:
    "Choose tuning (even custom), enter frets and I'll tell you what chord it is.",
  label_tuning: "Tuning:",
  label_notation: "Notation:",
  label_language: "Language:",
  label_show_octave: "Show octave",
  notation_latin: "Latin (Do, Re, Mi...)",
  notation_anglo: "Anglo (C, D, E...)",
  label_tuning_name: "Tuning name:",
  placeholder_tuning_name: "My tuning",
  btn_save_tuning: "Save tuning",
  header_string: "String",
  header_tuning: "Tuning",
  header_fret: "Fret",
  header_note: "Note",
  string_label_prefix: "String",
  placeholder_fret: "0, 1, 3, x...",
  btn_calc: "Calculate chord",
  hint_text:
    "• Leave fret empty or type <strong>x</strong> if string is muted.<br /> • Use numbers <strong>0 to 24</strong> for frets.<br /> • In tuning, click each string to choose the note from a dropdown.<br /> • Enter a name and click <strong>Save tuning</strong> to save it in the browser.",
  msg_error_data: "Data error",
  msg_no_notes: "No notes",
  tuning_e_std: "E standard",
  tuning_drop_d: "Drop D",
  tuning_d_std: "D standard",
  tuning_drop_c: "Drop C",
  tuning_drop_b: "Drop B",
  tuning_drop_a: "Drop A",
  group_builtin: "Built-in",
  group_custom: "Custom",
  chord_major: "Major",
  chord_minor: "Minor",
  chord_dim: "Diminished",
  chord_aug: "Augmented",
  chord_sus2: "Suspended 2",
  chord_sus4: "Suspended 4",
  chord_maj7: "Major 7",
  chord_m7: "Minor 7",
  chord_dom7: "Dominant 7",
  chord_m7b5: "Half-diminished 7",
  chord_dim7: "Diminished 7",
  chord_mmaj7: "Minor Major 7",
  chord_maj6: "Major 6",
  chord_m6: "Minor 6",
  single_note: "Single note",
  power_chord: "Power chord",
  msg_enter_name: "Please enter a name for the custom tuning.",
  msg_error_reading_strings: "Could not read string tuning.",
  msg_unknown_chord: "Unknown chord",
  msg_notes_detected: "Notes detected: ",
  msg_type: "Type: ",
  msg_notes: " | Notes: ",
};
